package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDataTask<M extends BaseDataTask<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 状态:0=停止,1=启动
	 */
	public void setState(java.lang.Integer state) {
		set("state", state);
	}
	
	/**
	 * 状态:0=停止,1=启动
	 */
	public java.lang.Integer getState() {
		return getInt("state");
	}

	/**
	 * 名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 表达式
	 */
	public void setExp(java.lang.String exp) {
		set("exp", exp);
	}
	
	/**
	 * 表达式
	 */
	public java.lang.String getExp() {
		return getStr("exp");
	}

	/**
	 * 实现类
	 */
	public void setClazz(java.lang.String clazz) {
		set("clazz", clazz);
	}
	
	/**
	 * 实现类
	 */
	public java.lang.String getClazz() {
		return getStr("clazz");
	}

	/**
	 * 说明
	 */
	public void setInfo(java.lang.String info) {
		set("info", info);
	}
	
	/**
	 * 说明
	 */
	public java.lang.String getInfo() {
		return getStr("info");
	}

}
