package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDataAppVersion<M extends BaseDataAppVersion<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 版本号
	 */
	public void setVersion(java.lang.String version) {
		set("version", version);
	}
	
	/**
	 * 版本号
	 */
	public java.lang.String getVersion() {
		return getStr("version");
	}

	/**
	 * 说明
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 说明
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 下载地址
	 */
	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	/**
	 * 下载地址
	 */
	public java.lang.String getUrl() {
		return getStr("url");
	}

}
