package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTraceBasedataProductline<M extends BaseTraceBasedataProductline<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 产线
	 */
	public void setProductline(java.lang.String productline) {
		set("productline", productline);
	}
	
	/**
	 * 产线
	 */
	public java.lang.String getProductline() {
		return getStr("productline");
	}

	/**
	 * 车间编号
	 */
	public void setWorkshopId(java.lang.Integer workshopId) {
		set("workshop_id", workshopId);
	}
	
	/**
	 * 车间编号
	 */
	public java.lang.Integer getWorkshopId() {
		return getInt("workshop_id");
	}

}
