package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTraceBasedataProduct<M extends BaseTraceBasedataProduct<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 成品件号
	 */
	public void setProductNo(java.lang.String productNo) {
		set("product_no", productNo);
	}
	
	/**
	 * 成品件号
	 */
	public java.lang.String getProductNo() {
		return getStr("product_no");
	}

	/**
	 * 零件描述
	 */
	public void setProductDesc(java.lang.String productDesc) {
		set("product_desc", productDesc);
	}
	
	/**
	 * 零件描述
	 */
	public java.lang.String getProductDesc() {
		return getStr("product_desc");
	}

	/**
	 * 产线编号
	 */
	public void setProductlineId(java.lang.Integer productlineId) {
		set("productline_id", productlineId);
	}
	
	/**
	 * 产线编号
	 */
	public java.lang.Integer getProductlineId() {
		return getInt("productline_id");
	}

}
