package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTraceBasedataProductRule<M extends BaseTraceBasedataProductRule<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 产品编号
	 */
	public void setProductId(java.lang.Integer productId) {
		set("product_id", productId);
	}
	
	/**
	 * 产品编号
	 */
	public java.lang.Integer getProductId() {
		return getInt("product_id");
	}

	/**
	 * 产品长度
	 */
	public void setProductLength(java.lang.String productLength) {
		set("product_length", productLength);
	}
	
	/**
	 * 产品长度
	 */
	public java.lang.String getProductLength() {
		return getStr("product_length");
	}

	/**
	 * 产品固定字段
	 */
	public void setProductRule(java.lang.String productRule) {
		set("product_rule", productRule);
	}
	
	/**
	 * 产品固定字段
	 */
	public java.lang.String getProductRule() {
		return getStr("product_rule");
	}

	/**
	 * 盒标签长度
	 */
	public void setBoxLength(java.lang.String boxLength) {
		set("box_length", boxLength);
	}
	
	/**
	 * 盒标签长度
	 */
	public java.lang.String getBoxLength() {
		return getStr("box_length");
	}

	/**
	 * 盒标签固定字段
	 */
	public void setBoxRule(java.lang.String boxRule) {
		set("box_rule", boxRule);
	}
	
	/**
	 * 盒标签固定字段
	 */
	public java.lang.String getBoxRule() {
		return getStr("box_rule");
	}

	/**
	 * 打包数量
	 */
	public void setQuantity(java.lang.String quantity) {
		set("quantity", quantity);
	}
	
	/**
	 * 打包数量
	 */
	public java.lang.String getQuantity() {
		return getStr("quantity");
	}

}
