package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTraceBasedataPart<M extends BaseTraceBasedataPart<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 零部件号
	 */
	public void setPartNo(java.lang.String partNo) {
		set("part_no", partNo);
	}
	
	/**
	 * 零部件号
	 */
	public java.lang.String getPartNo() {
		return getStr("part_no");
	}

	/**
	 * 零件描述
	 */
	public void setPartDesc(java.lang.String partDesc) {
		set("part_desc", partDesc);
	}
	
	/**
	 * 零件描述
	 */
	public java.lang.String getPartDesc() {
		return getStr("part_desc");
	}

	/**
	 * 产品编号
	 */
	public void setProductId(java.lang.Integer productId) {
		set("product_id", productId);
	}
	
	/**
	 * 产品编号
	 */
	public java.lang.Integer getProductId() {
		return getInt("product_id");
	}

	/**
	 * 消耗数量
	 */
	public void setConsumptionQuantity(java.lang.String consumptionQuantity) {
		set("consumption_quantity", consumptionQuantity);
	}
	
	/**
	 * 消耗数量
	 */
	public java.lang.String getConsumptionQuantity() {
		return getStr("consumption_quantity");
	}

	/**
	 * 清洗数量
	 */
	public void setFeedingQuantity(java.lang.String feedingQuantity) {
		set("feeding_quantity", feedingQuantity);
	}
	
	/**
	 * 清洗数量
	 */
	public java.lang.String getFeedingQuantity() {
		return getStr("feeding_quantity");
	}

	/**
	 * 是否清洗管控0=否1=是
	 */
	public void setIsDisplay(java.lang.Integer isDisplay) {
		set("is_display", isDisplay);
	}
	
	/**
	 * 是否清洗管控0=否1=是
	 */
	public java.lang.Integer getIsDisplay() {
		return getInt("is_display");
	}

}
