package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTraceWorkflowCustomerQrcodeRule<M extends BaseTraceWorkflowCustomerQrcodeRule<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 零件号
	 */
	public void setProductno(java.lang.String productno) {
		set("productno", productno);
	}
	
	/**
	 * 零件号
	 */
	public java.lang.String getProductno() {
		return getStr("productno");
	}

	/**
	 * 零件名称
	 */
	public void setProductname(java.lang.String productname) {
		set("productname", productname);
	}
	
	/**
	 * 零件名称
	 */
	public java.lang.String getProductname() {
		return getStr("productname");
	}

	/**
	 * 基地/包装/客户/产品状态区分
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 基地/包装/客户/产品状态区分
	 */
	public java.lang.String getType() {
		return getStr("type");
	}

	/**
	 * 内部二维码固定内容
	 */
	public void setInsideCodeFixed(java.lang.String insideCodeFixed) {
		set("inside_code_fixed", insideCodeFixed);
	}
	
	/**
	 * 内部二维码固定内容
	 */
	public java.lang.String getInsideCodeFixed() {
		return getStr("inside_code_fixed");
	}

	/**
	 * 内部二维码长度
	 */
	public void setInsideCodeLength(java.lang.String insideCodeLength) {
		set("inside_code_length", insideCodeLength);
	}
	
	/**
	 * 内部二维码长度
	 */
	public java.lang.String getInsideCodeLength() {
		return getStr("inside_code_length");
	}

	/**
	 * 客户二维码固定内容
	 */
	public void setCustomerCodeFixed(java.lang.String customerCodeFixed) {
		set("customer_code_fixed", customerCodeFixed);
	}
	
	/**
	 * 客户二维码固定内容
	 */
	public java.lang.String getCustomerCodeFixed() {
		return getStr("customer_code_fixed");
	}

	/**
	 * 客户二维码长度
	 */
	public void setCustomerCodeLength(java.lang.String customerCodeLength) {
		set("customer_code_length", customerCodeLength);
	}
	
	/**
	 * 客户二维码长度
	 */
	public java.lang.String getCustomerCodeLength() {
		return getStr("customer_code_length");
	}

	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
