package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTraceWorkflowMaterialScrapDetail<M extends BaseTraceWorkflowMaterialScrapDetail<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 报废任务ID
	 */
	public void setAssembleId(java.lang.Integer assembleId) {
		set("assemble_id", assembleId);
	}
	
	/**
	 * 报废任务ID
	 */
	public java.lang.Integer getAssembleId() {
		return getInt("assemble_id");
	}

	/**
	 * 子部件
	 */
	public void setPartNo(java.lang.String partNo) {
		set("part_no", partNo);
	}
	
	/**
	 * 子部件
	 */
	public java.lang.String getPartNo() {
		return getStr("part_no");
	}

	/**
	 * 子部件批次号
	 */
	public void setBatchNo(java.lang.String batchNo) {
		set("batch_no", batchNo);
	}
	
	/**
	 * 子部件批次号
	 */
	public java.lang.String getBatchNo() {
		return getStr("batch_no");
	}

	/**
	 * 数量
	 */
	public void setQuantity(java.lang.Integer quantity) {
		set("quantity", quantity);
	}
	
	/**
	 * 数量
	 */
	public java.lang.Integer getQuantity() {
		return getInt("quantity");
	}

}
