package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSerialNumber<M extends BaseSerialNumber<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 收货单号
	 */
	public void setPartInvoiceNo(java.lang.Integer partInvoiceNo) {
		set("part_invoice_no", partInvoiceNo);
	}
	
	/**
	 * 收货单号
	 */
	public java.lang.Integer getPartInvoiceNo() {
		return getInt("part_invoice_no");
	}

	/**
	 * 检验单号
	 */
	public void setPartCheckNo(java.lang.Integer partCheckNo) {
		set("part_check_no", partCheckNo);
	}
	
	/**
	 * 检验单号
	 */
	public java.lang.Integer getPartCheckNo() {
		return getInt("part_check_no");
	}

	/**
	 * 配料单号
	 */
	public void setIngredientPlanNo(java.lang.Integer ingredientPlanNo) {
		set("ingredient_plan_no", ingredientPlanNo);
	}
	
	/**
	 * 配料单号
	 */
	public java.lang.Integer getIngredientPlanNo() {
		return getInt("ingredient_plan_no");
	}

	/**
	 * 客户订单号
	 */
	public void setCustOrderNo(java.lang.Integer custOrderNo) {
		set("cust_order_no", custOrderNo);
	}
	
	/**
	 * 客户订单号
	 */
	public java.lang.Integer getCustOrderNo() {
		return getInt("cust_order_no");
	}

}
