package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTraceBasedataWorkshop<M extends BaseTraceBasedataWorkshop<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 车间
	 */
	public void setWorkshop(java.lang.String workshop) {
		set("workshop", workshop);
	}
	
	/**
	 * 车间
	 */
	public java.lang.String getWorkshop() {
		return getStr("workshop");
	}

}
