package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYwTestSon<M extends BaseYwTestSon<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 产线ID
	 */
	public void setYwTestId(java.lang.Integer ywTestId) {
		set("yw_test_id", ywTestId);
	}
	
	/**
	 * 产线ID
	 */
	public java.lang.Integer getYwTestId() {
		return getInt("yw_test_id");
	}

	/**
	 * 工序号
	 */
	public void setNo(java.lang.String no) {
		set("no", no);
	}
	
	/**
	 * 工序号
	 */
	public java.lang.String getNo() {
		return getStr("no");
	}

	/**
	 * 工序名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 工序名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

}
