package com.ray.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JBolt, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("data_app_version", "id", DataAppVersion.class);
		arp.addMapping("data_button", "id", DataButton.class);
		arp.addMapping("data_field", "id", DataField.class);
		arp.addMapping("data_object", "id", DataObject.class);
		arp.addMapping("data_task", "id", DataTask.class);
		arp.addMapping("dicts", "id", Dicts.class);
		arp.addMapping("file", "id", File.class);
		arp.addMapping("menu", "id", Menu.class);
		arp.addMapping("permissions", "id", Permissions.class);
		arp.addMapping("role_permission", "id", RolePermission.class);
		arp.addMapping("roles", "id", Roles.class);
		arp.addMapping("serial_number", "id", SerialNumber.class);
		arp.addMapping("trace_basedata_part", "id", TraceBasedataPart.class);
		arp.addMapping("trace_basedata_product", "id", TraceBasedataProduct.class);
		arp.addMapping("trace_basedata_product_gp12rule", "id", TraceBasedataProductGp12rule.class);
		arp.addMapping("trace_basedata_product_rule", "id", TraceBasedataProductRule.class);
		arp.addMapping("trace_basedata_productline", "id", TraceBasedataProductline.class);
		arp.addMapping("trace_basedata_workshop", "id", TraceBasedataWorkshop.class);
		arp.addMapping("trace_workflow_assemble", "id", TraceWorkflowAssemble.class);
		arp.addMapping("trace_workflow_assemble_detail", "id", TraceWorkflowAssembleDetail.class);
		arp.addMapping("trace_workflow_cleanbinding", "id", TraceWorkflowCleanbinding.class);
		arp.addMapping("trace_workflow_customer_qrcode_history", "id", TraceWorkflowCustomerQrcodeHistory.class);
		arp.addMapping("trace_workflow_customer_qrcode_rule", "id", TraceWorkflowCustomerQrcodeRule.class);
		arp.addMapping("trace_workflow_equipfeeding", "id", TraceWorkflowEquipfeeding.class);
		arp.addMapping("trace_workflow_material_scrap", "id", TraceWorkflowMaterialScrap.class);
		arp.addMapping("trace_workflow_material_scrap_detail", "id", TraceWorkflowMaterialScrapDetail.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("user_role", "id", UserRole.class);
		arp.addMapping("washing_plan_date", "id", WashingPlanDate.class);
		arp.addMapping("washing_plan_parts", "id", WashingPlanParts.class);
		arp.addMapping("yw_test", "id", YwTest.class);
		arp.addMapping("yw_test_son", "id", YwTestSon.class);
	}
}

