package com.ray.common.model;

import com.ray.common.model.base.BaseTraceBasedataPart;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class TraceBasedataPart extends BaseTraceBasedataPart<TraceBasedataPart> {
	//建议将dao放在Service中只用作查询 
	public static final TraceBasedataPart dao = new TraceBasedataPart().dao();
	//在Service中声明 可直接复制过去使用
	//private TraceBasedataPart dao = new TraceBasedataPart().dao();  
}
