package com.ray.common.model;

import com.ray.common.model.base.BaseTraceBasedataProductGp12rule;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class TraceBasedataProductGp12rule extends BaseTraceBasedataProductGp12rule<TraceBasedataProductGp12rule> {
	//建议将dao放在Service中只用作查询 
	public static final TraceBasedataProductGp12rule dao = new TraceBasedataProductGp12rule().dao();
	//在Service中声明 可直接复制过去使用
	//private TraceBasedataProductGp12rule dao = new TraceBasedataProductGp12rule().dao();  
}
