package com.ray.common.model;

import com.ray.common.model.base.BaseTraceWorkflowMaterialScrapDetail;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class TraceWorkflowMaterialScrapDetail extends BaseTraceWorkflowMaterialScrapDetail<TraceWorkflowMaterialScrapDetail> {
	//建议将dao放在Service中只用作查询 
	public static final TraceWorkflowMaterialScrapDetail dao = new TraceWorkflowMaterialScrapDetail().dao();
	//在Service中声明 可直接复制过去使用
	//private TraceWorkflowMaterialScrapDetail dao = new TraceWorkflowMaterialScrapDetail().dao();  
}
