package com.ray.common.model;

import com.ray.common.model.base.BaseTraceWorkflowCleanbinding;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class TraceWorkflowCleanbinding extends BaseTraceWorkflowCleanbinding<TraceWorkflowCleanbinding> {
	//建议将dao放在Service中只用作查询 
	public static final TraceWorkflowCleanbinding dao = new TraceWorkflowCleanbinding().dao();
	//在Service中声明 可直接复制过去使用
	//private TraceWorkflowCleanbinding dao = new TraceWorkflowCleanbinding().dao();  
}
