package com.ray.common.model;

import com.ray.common.model.base.BaseTraceWorkflowMaterialScrap;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class TraceWorkflowMaterialScrap extends BaseTraceWorkflowMaterialScrap<TraceWorkflowMaterialScrap> {
	//建议将dao放在Service中只用作查询 
	public static final TraceWorkflowMaterialScrap dao = new TraceWorkflowMaterialScrap().dao();
	//在Service中声明 可直接复制过去使用
	//private TraceWorkflowMaterialScrap dao = new TraceWorkflowMaterialScrap().dao();  
}
