package com.ray.common.model;

import com.ray.common.model.base.BaseTraceWorkflowCustomerQrcodeRule;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class TraceWorkflowCustomerQrcodeRule extends BaseTraceWorkflowCustomerQrcodeRule<TraceWorkflowCustomerQrcodeRule> {
	//建议将dao放在Service中只用作查询 
	public static final TraceWorkflowCustomerQrcodeRule dao = new TraceWorkflowCustomerQrcodeRule().dao();
	//在Service中声明 可直接复制过去使用
	//private TraceWorkflowCustomerQrcodeRule dao = new TraceWorkflowCustomerQrcodeRule().dao();  
}
