package com.ray.common.model;

import com.ray.common.model.base.BaseTraceWorkflowEquipfeeding;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class TraceWorkflowEquipfeeding extends BaseTraceWorkflowEquipfeeding<TraceWorkflowEquipfeeding> {
	//建议将dao放在Service中只用作查询 
	public static final TraceWorkflowEquipfeeding dao = new TraceWorkflowEquipfeeding().dao();
	//在Service中声明 可直接复制过去使用
	//private TraceWorkflowEquipfeeding dao = new TraceWorkflowEquipfeeding().dao();  
}
