package com.ray.common.model;

import com.ray.common.model.base.BaseTraceWorkflowCustomerQrcodeHistory;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class TraceWorkflowCustomerQrcodeHistory extends BaseTraceWorkflowCustomerQrcodeHistory<TraceWorkflowCustomerQrcodeHistory> {
	//建议将dao放在Service中只用作查询 
	public static final TraceWorkflowCustomerQrcodeHistory dao = new TraceWorkflowCustomerQrcodeHistory().dao();
	//在Service中声明 可直接复制过去使用
	//private TraceWorkflowCustomerQrcodeHistory dao = new TraceWorkflowCustomerQrcodeHistory().dao();  
}
