package com.ray.common.model;

import com.ray.common.model.base.BaseTraceWorkflowAssembleDetail;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class TraceWorkflowAssembleDetail extends BaseTraceWorkflowAssembleDetail<TraceWorkflowAssembleDetail> {
	//建议将dao放在Service中只用作查询 
	public static final TraceWorkflowAssembleDetail dao = new TraceWorkflowAssembleDetail().dao();
	//在Service中声明 可直接复制过去使用
	//private TraceWorkflowAssembleDetail dao = new TraceWorkflowAssembleDetail().dao();  
}
