package com.ray.common.model;

import com.ray.common.model.base.BaseTraceBasedataProductRule;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class TraceBasedataProductRule extends BaseTraceBasedataProductRule<TraceBasedataProductRule> {
	//建议将dao放在Service中只用作查询 
	public static final TraceBasedataProductRule dao = new TraceBasedataProductRule().dao();
	//在Service中声明 可直接复制过去使用
	//private TraceBasedataProductRule dao = new TraceBasedataProductRule().dao();  
}
