package com.ray.common.model;

import com.ray.common.model.base.BaseTraceBasedataWorkshop;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class TraceBasedataWorkshop extends BaseTraceBasedataWorkshop<TraceBasedataWorkshop> {
	//建议将dao放在Service中只用作查询 
	public static final TraceBasedataWorkshop dao = new TraceBasedataWorkshop().dao();
	//在Service中声明 可直接复制过去使用
	//private TraceBasedataWorkshop dao = new TraceBasedataWorkshop().dao();  
}
