package com.ray.common.model;

import com.ray.common.model.base.BaseTraceBasedataProductline;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class TraceBasedataProductline extends BaseTraceBasedataProductline<TraceBasedataProductline> {
	//建议将dao放在Service中只用作查询 
	public static final TraceBasedataProductline dao = new TraceBasedataProductline().dao();
	//在Service中声明 可直接复制过去使用
	//private TraceBasedataProductline dao = new TraceBasedataProductline().dao();  
}
