package com.ray.common.model;

import com.ray.common.model.base.BaseWashingPlanParts;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class WashingPlanParts extends BaseWashingPlanParts<WashingPlanParts> {
	//建议将dao放在Service中只用作查询 
	public static final WashingPlanParts dao = new WashingPlanParts().dao();
	//在Service中声明 可直接复制过去使用
	//private WashingPlanParts dao = new WashingPlanParts().dao();  
}
